Fix B64 decode error at playlist creation
```
 Error Contents: a bytes-like object is required, not 'str'
 Traceback (most recent call last):
 File "/storage/.kodi/addons/script.plex/lib/windows/kodigui.py", line 105, in onInit
 self.onFirstInit()
 File "/storage/.kodi/addons/script.plex/lib/windows/musicplayer.py", line 64, in onFirstInit
 self.play()
 File "/storage/.kodi/addons/script.plex/lib/windows/musicplayer.py", line 152, in play
 player.PLAYER.playAudioPlaylist(self.playlist, startpos=list(self.playlist.items()).index(self.track), fanart=fanart)
 File "/storage/.kodi/addons/script.plex/lib/player.py", line 858, in playAudioPlaylist
 url, li = self.createTrackListItem(track, fanart, index=index)
 File "/storage/.kodi/addons/script.plex/lib/player.py", line 874, in createTrackListItem
 data = base64.urlsafe_b64encode(track.serialize())
 File "/usr/lib/python3.8/base64.py", line 118, in urlsafe_b64encode
 File "/usr/lib/python3.8/base64.py", line 58, in b64encode
 TypeError: a bytes-like object is required, not 'str'
```